#!/usr/bin/env bash
# Configure Nginx to run as nginx user on port 8080

# Set nginx user in config
sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf

# Change to port 8080
sed -i "s/listen 80;/listen 8080;/" /etc/nginx/sites-available/default
sed -i "s/listen \[::\]:80;/listen [::]:8080;/" /etc/nginx/sites-available/default

# Restart Nginx
pkill nginx
sudo -u nginx /usr/sbin/nginx
