#!/usr/bin/env bash
# Configures Nginx to run as the nginx user and listen on port 8080

# Change the user in nginx.conf from root to nginx
sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf

# Change listening port from 80 to 8080 in default site configuration
sed -i "s/listen 80 default_server;/listen 8080 default_server;/" /etc/nginx/sites-available/default
sed -i "s/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/" /etc/nginx/sites-available/default

# Kill any existing Nginx processes
pkill apache2

# Start Nginx as nginx user
chmod 644 /etc/nginx/nginx.conf
su nginx -s /bin/bash -c 'service nginx restart'
