#!/usr/bin/env bash
# Installs and configures Nginx to return "Holberton School" at the root

# Update and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Allow HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Overwrite the default Nginx root index file with the required content
sudo sh -c 'echo "Holberton School" > /var/www/html/index.nginx-debian.html'

# Restart Nginx
sudo service nginx restart
