#!/usr/bin/env bash
# Configures a new Ubuntu machine to install and setup Nginx

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create a simple HTML page with "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.html

# Ensure nginx is configured to listen on port 80 (default configuration should handle this)
# Start nginx service
service nginx start
