#!/usr/bin/env bash
# Installs Nginx and configures a 301 redirect from /redirect_me

# Install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Add redirect block to default site config
sudo sed -i '/^\s*server {/a \\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Restart nginx using service
sudo service nginx restart
